services:
  my-notes-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: run/secrets/db-password
    ports:
      - 5432:5432
    secrets:
      - db-password

secrets:
  db-password:
    file: ./db-password.txt
