services:
  my-notes-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: my-notes-db
    ports:
      - 5432:5432
    secrets:
      - db_password

secrets:
  db_password:
    environment: "DB_PASSWORD"
